/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "string.h"

#include "../MCAL/RCC/RCC_Interface.h"
#include "../MCAL/TIMERS/TIMERS_Interface.h"

#include "../ECUAL/LED/LED_Interface.h"
#include "../Services/Bootloader.h"


LED_t green = {PORTA, 0};

void SystemInitialize(void);
void Blink(void);
void SerialTest(void);

int main(void)
{
	SystemInitialize();

	SerialTest();
	BL_getCommand();
	while(1)
	{
		Blink();
	}
}

void SystemInitialize(void)
{
	RCC_voidInit();

	RCC_voidPeripheralEnable(GPIOA_EN);
	RCC_voidPeripheralEnable(GPIOB_EN);
	RCC_voidPeripheralEnable(TIM2_EN);
	RCC_voidPeripheralEnable(USART1_EN);
	RCC_voidPeripheralEnable(USART6_EN);

	LED_voidInit(&green);
}

void Blink(void)
{
	LED_voidToggle(&green);
	TIMERS_voidDelayMilliSec(500);
}
